hiscox_etl:
  outputs:
    dev:
      type: databricks
      catalog: hive_metastore
      schema: hiscox_etl_dev
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4
      connect_retries: 5
      connect_timeout: 60
      retry_all: true
      
    staging:
      type: databricks
      catalog: hive_metastore
      schema: hiscox_etl_staging
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 8
      connect_retries: 5
      connect_timeout: 60
      retry_all: true
      
    prod:
      type: databricks
      catalog: hive_metastore
      schema: hiscox_etl_prod
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 16
      connect_retries: 5
      connect_timeout: 60
      retry_all: true

  target: dev
